# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-02 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
